# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: docs
          git-user: mfpjayb
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
