name: Docusaurus CI Deploy

on:
  push:
    branches: ["master"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to github pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment only
concurrency:
  group: "pages"
  cancel-in-progress: true

# jobs:
#   build:

#     runs-on: windows-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: cd docs && npm install && npm run deploy-page

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install && npm run build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "docs/build"
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
        
  

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: redkubes/docusaurus-deploy-action@v1.2
#         with:
#           source-folder: docs
#           git-user: mfpjayb
#           git-password: ${{ secrets.PASSWORD }}
#           deployment-branch: gh-pages
